package day42_Exceptions;

public class ThrowsKeyWord2 {

    public static void main(String[] args) throws ArithmeticException{

        //  we use throws keyword only for checked exceptions
        // below we have unchecked exception even I applied
        // throw keyword  still have exception

        System.out.println("Test started");

      //  System.out.println(8/0);

        System.out.println("Test completed");




    }
}
